### ISSUE TITLE
Get Ready for Styled Prototype

### ISSUE THREAD

**Issue by martinrebo** [martinrebo/gamelab33#5]
### Task: Create a Styled Prototype

- [x] Add 5 Complete Cards to the Database with real Information

- [x]  Refactor  CSS Styles (Light - Dark - Hell/Matrix/BlackHole)

- [x] Router + Refactor Code + HOC + Folder Structure

- [ ] Choose Domain Name 

Next Steps: User Authorization + Paths
